// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    user_id, title, content, published_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, title, content, published_at, created_at, updated_at
`

type CreateArticleParams struct {
	UserID      int64            `json:"user_id"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, user_id, title, content, published_at, created_at, updated_at FROM articles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, user_id, title, content, published_at, created_at, updated_at FROM articles
ORDER BY id
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByUser = `-- name: ListArticlesByUser :many
SELECT id, user_id, title, content, published_at, created_at, updated_at FROM articles
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListArticlesByUser(ctx context.Context, userID int64) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET user_id = $1, title = $2, content = $3, published_at = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, user_id, title, content, published_at, created_at, updated_at
`

type UpdateArticleParams struct {
	UserID      int64            `json:"user_id"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	ID          int64            `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.PublishedAt,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
