// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Article struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"user_id"`
	Title       string           `json:"title"`
	Content     string           `json:"content"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Comment struct {
	ID           int64            `json:"id"`
	ArticleID    int64            `json:"article_id"`
	UserID       *int64           `json:"user_id"`
	TempUserName *string          `json:"temp_user_name"`
	Content      string           `json:"content"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
