// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListArticles(ctx context.Context) ([]Article, error)
	ListArticlesByUser(ctx context.Context, userID int64) ([]Article, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
